#!/usr/bin/python

import sys
import os

if __name__ == '__main__':
	if os.geteuid() != 0:
		sys.exit("Have no root\'s permission, exit.")

	if len(sys.argv) == 1:
		os.system('simple-mtpfs /mnt/')
	elif len(sys.argv) == 2 and sys.argv[1] == '-u':
		os.system('fusermount -u /mnt')
